"""Generate the LiteLLM proxy config from config/plans.yaml.

One source of truth: caps, lane order, credentials and expiry all come from
plans.yaml, so there is no second file to keep in sync. Run it at container
start (the entrypoint does) or by hand:

    python -m switchyard.gen_litellm config/plans.yaml config/litellm.generated.yaml
"""
from __future__ import annotations

import sys

import yaml

from .models import load


def build(plans_path: str) -> dict:
    with open(plans_path) as fh:
        raw = yaml.safe_load(fh)
    reg = load(plans_path)
    transport = raw.get("deployments") or {}

    model_list: list[dict] = []
    for key, plan in reg.plans.items():
        params = dict(transport.get(key) or {})
        if not params:
            continue
        # A per-deployment cap as a backstop: Switchyard's slot table is the
        # real gate, but if a caller names a deployment directly (bypassing
        # the lane) we still refuse to exceed the plan's connection limit.
        params["max_parallel_requests"] = plan.max_parallel
        model_list.append({
            "model_name": plan.deployment,
            "litellm_params": params,
            "model_info": {
                "switchyard_plan": key,
                "monthly_cost": plan.monthly_cost,
                "expires": str(plan.expires) if plan.expires else None,
                "auth": plan.auth,
            },
        })

    # Lane aliases exist so that /v1/models advertises the lanes and virtual
    # key model-access checks pass. The pre-call hook overwrites the target
    # before routing, so the deployment named here is only a safety default.
    for lane_key in reg.lanes:
        members = reg.lane_members(lane_key)
        if not members:
            continue
        first = members[0]
        model_list.append({
            "model_name": lane_key,
            "litellm_params": dict(transport.get(first.key) or {}),
            "model_info": {"switchyard_lane": lane_key, "default_plan": first.key},
        })

    # Mid-call failover. Switchyard picks the entry point; if that call dies
    # in flight, LiteLLM walks the rest of the lane rather than failing the
    # request. The hook's cooldown still removes the dead plan from future
    # picks, so this is belt-and-braces, not the primary mechanism.
    fallbacks: list[dict[str, list[str]]] = []
    for lane_key in reg.lanes:
        members = reg.lane_members(lane_key)
        for i, plan in enumerate(members):
            tail = [p.deployment for p in members[i + 1:]]
            if tail:
                fallbacks.append({plan.deployment: tail})
        if members:
            fallbacks.append({lane_key: [p.deployment for p in members]})

    return {
        "model_list": model_list,
        "litellm_settings": {
            "callbacks": ["switchyard.hooks.switchyard_handler"],
            "drop_params": True,
            "request_timeout": 600,
            "num_retries": 0,   # Switchyard owns retry placement, not LiteLLM
        },
        "router_settings": {
            "enable_pre_call_checks": True,
            "routing_strategy": "simple-shuffle",
            "fallbacks": fallbacks,
            "allowed_fails": 1,
            "cooldown_time": 60,   # short: the real cooldowns live in Redis
            "redis_host": "os.environ/REDIS_HOST",
            "redis_port": "os.environ/REDIS_PORT",
        },
        "general_settings": {
            "master_key": "os.environ/LITELLM_MASTER_KEY",
            "database_url": "os.environ/DATABASE_URL",
        },
    }


def main() -> int:
    src = sys.argv[1] if len(sys.argv) > 1 else "config/plans.yaml"
    dst = sys.argv[2] if len(sys.argv) > 2 else "config/litellm.generated.yaml"
    cfg = build(src)
    header = (
        "# GENERATED by `python -m switchyard.gen_litellm` — do not edit.\n"
        "# Edit config/plans.yaml instead, then POST /admin/reload.\n"
    )
    with open(dst, "w") as fh:
        fh.write(header)
        yaml.safe_dump(cfg, fh, sort_keys=False, width=100)
    print(f"wrote {dst}: {len(cfg['model_list'])} entries, {len(cfg['router_settings']['fallbacks'])} fallback rules")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
